[2025-09-09 15:20:36] ERROR [database.php:100] | Called from: CustomerController.php:480: Database Query Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_active' in 'where clause' | Context: {"sql":"SELECT category_id, category, type, subtype \r\n                FROM complaint_categories \r\n                WHERE is_active = 1 \r\n                ORDER BY category, type, subtype","params":[],"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","caller_line":480,"caller_function":"fetchAll","file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php","line":100}
[2025-09-09 15:20:36] ERROR [Config.php:654] | Called from: index.php:51: EXCEPTION [database.php:110]: Database query failed | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php","line":110,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php(120): Database->query('SELECT category...', Array)\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php(480): Database->fetchAll('SELECT category...')\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php(165): CustomerController->getTicketCategories()\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): CustomerController->createTicket()\n#4 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@create...', Array)\n#5 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#6 {main}","caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php","caller_line":51}
[2025-09-09 15:26:48] ERROR [Config.php:634] | Called from: create-ticket.php:50: WARNING: Undefined array key "mobile" | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\create-ticket.php","line":50,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\create-ticket.php","caller_line":50}
[2025-09-09 15:26:48] ERROR [Config.php:634] | Called from: create-ticket.php:50: DEPRECATED: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\create-ticket.php","line":50,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\create-ticket.php","caller_line":50}
[2025-09-09 15:26:48] ERROR [Config.php:634] | Called from: create-ticket.php:57: WARNING: Undefined array key "company_name" | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\create-ticket.php","line":57,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\create-ticket.php","caller_line":57}
[2025-09-09 15:26:48] ERROR [Config.php:634] | Called from: create-ticket.php:57: DEPRECATED: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\create-ticket.php","line":57,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\create-ticket.php","caller_line":57}
[2025-09-09 16:50:25] ERROR [database.php:100] | Called from: ActivityLogger.php:36: Database Query Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sampark_db`.`activity_logs`, CONSTRAINT `activity_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) | Context: {"sql":"INSERT INTO activity_logs (\r\n                user_id, customer_id, user_role, action, description, \r\n                complaint_id, ip_address, user_agent, created_at\r\n            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW())","params":["CUST2025090001",null,"customer","customer_login",null,null,"::1","Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/139.0.0.0 Safari\/537.36"],"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\ActivityLogger.php","caller_line":36,"caller_function":"query","file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php","line":100}
[09-Sep-2025 16:50:25 Asia/Kolkata] Activity logging error: Database query failed
[2025-09-09 17:33:04] ERROR [Config.php:634] | Called from: ticket-details.php:106: WARNING: Undefined array key "gstin_number" | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","line":106,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","caller_line":106}
[2025-09-09 17:33:04] ERROR [Config.php:634] | Called from: ticket-details.php:163: DEPRECATED: ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","line":163,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","caller_line":163}
[2025-09-09 17:33:04] ERROR [Config.php:654]: EXCEPTION [ticket-details.php:250]: Call to undefined method CustomerController::getTransactionIcon() | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","line":250,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\BaseController.php(38): require_once()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php(156): BaseController->view('customer\/ticket...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): CustomerController->viewTicket('202509090001')\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@viewTi...', Array)\n#4 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#5 {main}"}
[2025-09-10 10:49:47] ERROR [database.php:100] | Called from: ActivityLogger.php:36: Database Query Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sampark_db`.`activity_logs`, CONSTRAINT `activity_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) | Context: {"sql":"INSERT INTO activity_logs (\r\n                user_id, customer_id, user_role, action, description, \r\n                complaint_id, ip_address, user_agent, created_at\r\n            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW())","params":["CUST2025090001",null,"customer","customer_login",null,null,"::1","Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/139.0.0.0 Safari\/537.36"],"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\ActivityLogger.php","caller_line":36,"caller_function":"query","file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php","line":100}
[10-Sep-2025 10:49:47 Asia/Kolkata] Activity logging error: Database query failed
[2025-09-10 11:42:20] ERROR [Config.php:657]: EXCEPTION [CustomerController.php:630]: Class "FileUploader" not found | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":630,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php(257): CustomerController->handleEvidenceUpload('202509100001', Array)\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): CustomerController->storeTicket()\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@storeT...', Array)\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#4 {main}"}
[2025-09-10 11:56:05] ERROR [Config.php:657]: EXCEPTION [CustomerController.php:630]: Class "FileUploader" not found | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":630,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php(257): CustomerController->handleEvidenceUpload('202509100001', Array)\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): CustomerController->storeTicket()\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@storeT...', Array)\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#4 {main}"}
[2025-09-10 11:56:35] ERROR [Config.php:657]: EXCEPTION [CustomerController.php:630]: Class "FileUploader" not found | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":630,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php(257): CustomerController->handleEvidenceUpload('202509100001', Array)\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): CustomerController->storeTicket()\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@storeT...', Array)\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#4 {main}"}
[2025-09-10 11:59:16] ERROR [Config.php:637] | Called from: ticket-details.php:106: WARNING: Undefined array key "gstin_number" | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","line":106,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","caller_line":106}
[2025-09-10 11:59:16] ERROR [Config.php:637] | Called from: ticket-details.php:163: DEPRECATED: ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","line":163,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","caller_line":163}
[2025-09-10 11:59:16] ERROR [Config.php:657]: EXCEPTION [ticket-details.php:250]: Call to undefined method CustomerController::getTransactionIcon() | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","line":250,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\BaseController.php(38): require_once()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php(157): BaseController->view('customer\/ticket...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): CustomerController->viewTicket('202509100001')\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@viewTi...', Array)\n#4 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#5 {main}"}
[2025-09-10 12:00:22] ERROR [Config.php:637] | Called from: ticket-details.php:106: WARNING: Undefined array key "gstin_number" | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","line":106,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","caller_line":106}
[2025-09-10 12:00:22] ERROR [Config.php:637] | Called from: ticket-details.php:163: DEPRECATED: ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","line":163,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","caller_line":163}
[2025-09-10 12:00:22] ERROR [Config.php:657]: EXCEPTION [ticket-details.php:250]: Call to undefined method CustomerController::getTransactionIcon() | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\views\\customer\\ticket-details.php","line":250,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\BaseController.php(38): require_once()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php(157): BaseController->view('customer\/ticket...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): CustomerController->viewTicket('202509100002')\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@viewTi...', Array)\n#4 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#5 {main}"}
[2025-09-10 13:24:34] ERROR [database.php:100] | Called from: ActivityLogger.php:36: Database Query Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sampark_db`.`activity_logs`, CONSTRAINT `activity_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) | Context: {"sql":"INSERT INTO activity_logs (\r\n                user_id, customer_id, user_role, action, description, \r\n                complaint_id, ip_address, user_agent, created_at\r\n            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW())","params":["CUST2025090001",null,"customer","customer_login",null,null,"::1","Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/139.0.0.0 Safari\/537.36"],"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\ActivityLogger.php","caller_line":36,"caller_function":"query","file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php","line":100}
[10-Sep-2025 13:24:34 Asia/Kolkata] Activity logging error: Database query failed
[2025-09-10 13:25:20] ERROR [Config.php:637] | Called from: FileUploader.php:174: WARNING: unlink(D:\Apps\XAMPP\htdocs\testfs\src/public/uploads/evidence/temp_202509100003_file1.jpeg): No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileUploader.php","line":174,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileUploader.php","caller_line":174}
[2025-09-10 13:25:20] ERROR [Config.php:637] | Called from: FileUploader.php:174: WARNING: unlink(D:\Apps\XAMPP\htdocs\testfs\src/public/uploads/evidence/temp_202509100003_file2.jpg): No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileUploader.php","line":174,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileUploader.php","caller_line":174}
[2025-09-10 13:25:20] ERROR [Config.php:637] | Called from: FileUploader.php:174: WARNING: unlink(D:\Apps\XAMPP\htdocs\testfs\src/public/uploads/evidence/temp_202509100003_file3.png): No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileUploader.php","line":174,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileUploader.php","caller_line":174}
[2025-09-10 14:40:52] ERROR [database.php:100] | Called from: ActivityLogger.php:36: Database Query Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sampark_db`.`activity_logs`, CONSTRAINT `activity_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) | Context: {"sql":"INSERT INTO activity_logs (\r\n                user_id, customer_id, user_role, action, description, \r\n                complaint_id, ip_address, user_agent, created_at\r\n            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW())","params":["CUST2025090001",null,"customer","customer_login",null,null,"::1","Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/139.0.0.0 Safari\/537.36"],"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\ActivityLogger.php","caller_line":36,"caller_function":"query","file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php","line":100}
[10-Sep-2025 14:40:52 Asia/Kolkata] Activity logging error: Database query failed
[2025-09-10 14:40:55] ERROR [Config.php:637] | Called from: CustomerController.php:8: WARNING: require_once(../utils/Validator.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":8,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","caller_line":8}
[2025-09-10 14:40:55] ERROR [Config.php:657]: EXCEPTION [CustomerController.php:8]: Failed opening required '../utils/Validator.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":8,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(108): require_once()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@create...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 14:41:00] ERROR [Config.php:637] | Called from: CustomerController.php:8: WARNING: require_once(../utils/Validator.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":8,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","caller_line":8}
[2025-09-10 14:41:00] ERROR [Config.php:657]: EXCEPTION [CustomerController.php:8]: Failed opening required '../utils/Validator.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":8,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(108): require_once()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@create...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 14:41:05] ERROR [Config.php:637] | Called from: CustomerController.php:8: WARNING: require_once(../utils/Validator.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":8,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","caller_line":8}
[2025-09-10 14:41:05] ERROR [Config.php:657]: EXCEPTION [CustomerController.php:8]: Failed opening required '../utils/Validator.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":8,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(108): require_once()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@create...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 14:41:07] ERROR [Config.php:637] | Called from: CustomerController.php:8: WARNING: require_once(../utils/Validator.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":8,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","caller_line":8}
[2025-09-10 14:41:07] ERROR [Config.php:657]: EXCEPTION [CustomerController.php:8]: Failed opening required '../utils/Validator.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":8,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(108): require_once()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@ticket...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 14:43:45] ERROR [Config.php:637] | Called from: CustomerController.php:9: WARNING: require_once(../utils/FileUploader.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":9,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","caller_line":9}
[2025-09-10 14:43:45] ERROR [Config.php:657]: EXCEPTION [CustomerController.php:9]: Failed opening required '../utils/FileUploader.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":9,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(108): require_once()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@create...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 15:00:07] ERROR [Config.php:648] | Called from: CustomerController.php:8: WARNING: require_once(../utils/Validator.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":8,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","caller_line":8}
[2025-09-10 15:00:07] ERROR [Config.php:668]: EXCEPTION [CustomerController.php:8]: Failed opening required '../utils/Validator.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\CustomerController.php","line":8,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(108): require_once()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@create...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 15:01:35] ERROR [Config.php:648] | Called from: FileCompressor.php:189: USER WARNING: ZipArchive class is not available | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php","line":189,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php","caller_line":189}
[2025-09-10 15:01:35] ERROR [Config.php:648] | Called from: FileUploader.php:174: WARNING: unlink(D:/Apps/XAMPP/htdocs/testfs/public/uploads/evidence/temp_202509100004_file1.jpeg): No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileUploader.php","line":174,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileUploader.php","caller_line":174}
[2025-09-10 15:23:35] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:23:35] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(124): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Api@getTicketUp...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 15:24:03] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:24:03] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(124): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Api@getTicketUp...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 15:24:04] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:24:04] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(124): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@ticket...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 15:24:04] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:24:04] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(68): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#2 {main}"}
[2025-09-10 15:24:04] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:24:04] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(68): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#2 {main}"}
[2025-09-10 15:27:03] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:03] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(124): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@ticket...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 15:27:03] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:03] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(68): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#2 {main}"}
[2025-09-10 15:27:03] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:03] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(68): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#2 {main}"}
[2025-09-10 15:27:04] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:04] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(124): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@ticket...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 15:27:04] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:04] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(68): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#2 {main}"}
[2025-09-10 15:27:04] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:04] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(68): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#2 {main}"}
[2025-09-10 15:27:06] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:06] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(124): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@viewTi...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 15:27:06] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:06] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(68): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#2 {main}"}
[2025-09-10 15:27:06] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:06] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(68): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#2 {main}"}
[2025-09-10 15:27:06] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:06] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(124): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@create...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 15:27:06] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:06] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(68): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#2 {main}"}
[2025-09-10 15:27:06] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:06] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(68): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#2 {main}"}
[2025-09-10 15:27:08] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:08] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(124): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@create...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 15:27:08] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:08] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(68): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#2 {main}"}
[2025-09-10 15:27:08] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:08] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(68): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#2 {main}"}
[2025-09-10 15:27:10] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:10] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(124): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Customer@create...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 15:27:10] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:10] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(68): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#2 {main}"}
[2025-09-10 15:27:10] ERROR [Config.php:648] | Called from: Router.php:147: WARNING: require_once(../views/errors/404.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":147}
[2025-09-10 15:27:10] ERROR [Config.php:668]: EXCEPTION [Router.php:147]: Failed opening required '../views/errors/404.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":147,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(68): Router->handleNotFound()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#2 {main}"}
[2025-09-10 15:41:42] ERROR [Config.php:648] | Called from: Router.php:37: WARNING: Undefined array key "REQUEST_METHOD" | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":37,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":37}
[2025-09-10 15:41:42] ERROR [Config.php:648] | Called from: Router.php:38: WARNING: Undefined array key "REQUEST_URI" | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":38,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":38}
[2025-09-10 15:41:42] ERROR [Config.php:648] | Called from: Router.php:38: DEPRECATED: parse_url(): Passing null to parameter #1 ($url) of type string is deprecated | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":38,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":38}
[2025-09-10 15:46:01] ERROR [Config.php:665] | Called from: Router.php:37: WARNING: Undefined array key "REQUEST_METHOD" | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":37,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":37}
[2025-09-10 15:46:01] ERROR [Config.php:665] | Called from: Router.php:38: WARNING: Undefined array key "REQUEST_URI" | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":38,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":38}
[2025-09-10 15:46:01] ERROR [Config.php:665] | Called from: Router.php:38: DEPRECATED: parse_url(): Passing null to parameter #1 ($url) of type string is deprecated | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","line":38,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php","caller_line":38}
[2025-09-10 15:53:11] ERROR [Config.php:665] | Called from: FileCompressor.php:189: USER WARNING: ZipArchive class is not available | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php","line":189,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php","caller_line":189}
[2025-09-10 15:53:56] ERROR [Config.php:665] | Called from: FileCompressor.php:189: USER WARNING: ZipArchive class is not available | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php","line":189,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php","caller_line":189}
[2025-09-10 15:54:57] ERROR [Config.php:665] | Called from: FileCompressor.php:189: USER WARNING: ZipArchive class is not available | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php","line":189,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php","caller_line":189}
[2025-09-10 15:55:08] ERROR [Config.php:665] | Called from: FileCompressor.php:189: USER WARNING: ZipArchive class is not available | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php","line":189,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php","caller_line":189}
[2025-09-10 15:56:37] ERROR [Config.php:665] | Called from: FileCompressor.php:189: USER WARNING: ZipArchive class is not available | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php","line":189,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php","caller_line":189}
[2025-09-10 16:01:27] ERROR [Config.php:685]: EXCEPTION [FileCompressor.php:216]: Invalid or uninitialized Zip object | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php","line":216,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php(216): ZipArchive->close()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php(176): compressWithZip('D:\\\\Apps\\\\XAMPP\\\\t...', 'C:\\\\WINDOWS\\\\TEMP...', 2097152)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\FileCompressor.php(50): compressImage('D:\\\\Apps\\\\XAMPP\\\\t...', 'C:\\\\WINDOWS\\\\TEMP...', 2097152, 'image\/png')\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\FileCompressionController.php(57): compressFile('D:\\\\Apps\\\\XAMPP\\\\t...', 2048)\n#4 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): FileCompressionController->compressFile()\n#5 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('FileCompression...', Array)\n#6 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#7 {main}"}
[2025-09-10 16:10:26] ERROR [database.php:100] | Called from: ActivityLogger.php:36: Database Query Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sampark_db`.`activity_logs`, CONSTRAINT `activity_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) | Context: {"sql":"INSERT INTO activity_logs (\r\n                user_id, customer_id, user_role, action, description, \r\n                complaint_id, ip_address, user_agent, created_at\r\n            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW())","params":["CUST2025090001",null,"customer","logout",null,null,"::1","Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/139.0.0.0 Safari\/537.36"],"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\ActivityLogger.php","caller_line":36,"caller_function":"query","file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php","line":100}
[10-Sep-2025 16:10:26 Asia/Kolkata] Activity logging error: Database query failed
[2025-09-10 16:10:56] ERROR [Config.php:665] | Called from: AdminController.php:8: WARNING: require_once(../utils/Validator.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\AdminController.php","line":8,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\AdminController.php","caller_line":8}
[2025-09-10 16:10:56] ERROR [Config.php:685]: EXCEPTION [AdminController.php:8]: Failed opening required '../utils/Validator.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\AdminController.php","line":8,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(108): require_once()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Admin@dashboard', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 16:11:03] ERROR [Config.php:665] | Called from: AdminController.php:8: WARNING: require_once(../utils/Validator.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\AdminController.php","line":8,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\AdminController.php","caller_line":8}
[2025-09-10 16:11:03] ERROR [Config.php:685]: EXCEPTION [AdminController.php:8]: Failed opening required '../utils/Validator.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\AdminController.php","line":8,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(108): require_once()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Admin@dashboard', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 16:11:10] ERROR [Config.php:665] | Called from: AdminController.php:8: WARNING: require_once(../utils/Validator.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\AdminController.php","line":8,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\AdminController.php","caller_line":8}
[2025-09-10 16:11:10] ERROR [Config.php:685]: EXCEPTION [AdminController.php:8]: Failed opening required '../utils/Validator.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\AdminController.php","line":8,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(108): require_once()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Admin@users', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 16:13:44] ERROR [Config.php:665] | Called from: AdminController.php:8: WARNING: require_once(D:\Apps\XAMPP\htdocs\testfs\src\controllers../utils/Validator.php): Failed to open stream: No such file or directory | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\AdminController.php","line":8,"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\AdminController.php","caller_line":8}
[2025-09-10 16:13:44] ERROR [Config.php:685]: EXCEPTION [AdminController.php:8]: Failed opening required 'D:\Apps\XAMPP\htdocs\testfs\src\controllers../utils/Validator.php' (include_path='D:\Apps\XAMPP\php\PEAR') | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\AdminController.php","line":8,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(108): require_once()\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Admin@users', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#3 {main}"}
[2025-09-10 16:16:20] ERROR [database.php:100] | Called from: ControllerController.php:729: Database Query Error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'division' in where clause is ambiguous | Context: {"sql":"SELECT c.complaint_id, c.priority, c.created_at, c.status,\r\n                       cat.category, cat.subtype,\r\n                       cust.name as customer_name,\r\n                       s.name as shed_name,\r\n                       TIMESTAMPDIFF(HOUR, c.created_at, NOW()) as hours_elapsed\r\n                FROM complaints c\r\n                LEFT JOIN complaint_categories cat ON c.category_id = cat.category_id\r\n                LEFT JOIN customers cust ON c.customer_id = cust.customer_id\r\n                LEFT JOIN shed s ON c.shed_id = s.shed_id\r\n                WHERE division = ? AND c.status IN ('pending', 'awaiting_info')\r\n                ORDER BY \r\n                    CASE WHEN c.priority = 'critical' THEN 1\r\n                         WHEN c.priority = 'high' THEN 2\r\n                         WHEN c.priority = 'medium' THEN 3\r\n                         ELSE 4\r\n                    END,\r\n                    c.created_at ASC\r\n                LIMIT ?","params":["Mumbai",10],"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\ControllerController.php","caller_line":729,"caller_function":"fetchAll","file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php","line":100}
[2025-09-10 16:16:20] ERROR [Config.php:685] | Called from: index.php:51: EXCEPTION [database.php:110]: Database query failed | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php","line":110,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php(120): Database->query('SELECT c.compla...', Array)\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\ControllerController.php(729): Database->fetchAll('SELECT c.compla...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\ControllerController.php(26): ControllerController->getPendingTickets(Array)\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): ControllerController->dashboard()\n#4 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Controller@dash...', Array)\n#5 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#6 {main}","caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php","caller_line":51}
[2025-09-10 16:16:29] ERROR [Config.php:685] | Called from: index.php:51: EXCEPTION [BaseController.php:40]: View not found: controller/tickets | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\BaseController.php","line":40,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\ControllerController.php(133): BaseController->view('controller\/tick...', Array)\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): ControllerController->tickets()\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Controller@tick...', Array)\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#4 {main}","caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php","caller_line":51}
[2025-09-10 16:34:06] ERROR [Config.php:685] | Called from: index.php:51: EXCEPTION [BaseController.php:44]: View not found: controller/tickets | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\BaseController.php","line":44,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\ControllerController.php(133): BaseController->view('controller\/tick...', Array)\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): ControllerController->tickets()\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Controller@tick...', Array)\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#4 {main}","caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php","caller_line":51}
[2025-09-10 16:34:12] ERROR [database.php:100] | Called from: ControllerController.php:729: Database Query Error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'division' in where clause is ambiguous | Context: {"sql":"SELECT c.complaint_id, c.priority, c.created_at, c.status,\r\n                       cat.category, cat.subtype,\r\n                       cust.name as customer_name,\r\n                       s.name as shed_name,\r\n                       TIMESTAMPDIFF(HOUR, c.created_at, NOW()) as hours_elapsed\r\n                FROM complaints c\r\n                LEFT JOIN complaint_categories cat ON c.category_id = cat.category_id\r\n                LEFT JOIN customers cust ON c.customer_id = cust.customer_id\r\n                LEFT JOIN shed s ON c.shed_id = s.shed_id\r\n                WHERE division = ? AND c.status IN ('pending', 'awaiting_info')\r\n                ORDER BY \r\n                    CASE WHEN c.priority = 'critical' THEN 1\r\n                         WHEN c.priority = 'high' THEN 2\r\n                         WHEN c.priority = 'medium' THEN 3\r\n                         ELSE 4\r\n                    END,\r\n                    c.created_at ASC\r\n                LIMIT ?","params":["Mumbai",10],"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\ControllerController.php","caller_line":729,"caller_function":"fetchAll","file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php","line":100}
[2025-09-10 16:34:12] ERROR [Config.php:685] | Called from: index.php:51: EXCEPTION [database.php:110]: Database query failed | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php","line":110,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php(120): Database->query('SELECT c.compla...', Array)\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\ControllerController.php(729): Database->fetchAll('SELECT c.compla...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\ControllerController.php(26): ControllerController->getPendingTickets(Array)\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): ControllerController->dashboard()\n#4 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Controller@dash...', Array)\n#5 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#6 {main}","caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php","caller_line":51}
[2025-09-10 16:34:14] ERROR [Config.php:685] | Called from: index.php:51: EXCEPTION [BaseController.php:44]: View not found: controller/reports | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\BaseController.php","line":44,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\ControllerController.php(650): BaseController->view('controller\/repo...', Array)\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): ControllerController->reports()\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Controller@repo...', Array)\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#4 {main}","caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php","caller_line":51}
[2025-09-10 16:34:24] ERROR [Config.php:685] | Called from: index.php:51: EXCEPTION [BaseController.php:44]: View not found: controller/profile | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\BaseController.php","line":44,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\ControllerController.php(668): BaseController->view('controller\/prof...', Array)\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): ControllerController->profile()\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Controller@prof...', Array)\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#4 {main}","caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php","caller_line":51}
[2025-09-10 16:40:12] ERROR [database.php:100] | Called from: ControllerController.php:703: Database Query Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c.division' in 'where clause' | Context: {"sql":"SELECT \n                    COUNT(*) as total,\n                    SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) as pending,\n                    SUM(CASE WHEN status = 'awaiting_info' THEN 1 ELSE 0 END) as awaiting_info,\n                    SUM(CASE WHEN status = 'awaiting_approval' THEN 1 ELSE 0 END) as awaiting_approval,\n                    SUM(CASE WHEN status = 'awaiting_feedback' THEN 1 ELSE 0 END) as awaiting_feedback,\n                    SUM(CASE WHEN status = 'closed' THEN 1 ELSE 0 END) as closed,\n                    SUM(CASE WHEN priority IN ('high', 'critical') THEN 1 ELSE 0 END) as high_priority_count,\n                    SUM(CASE WHEN sla_deadline IS NOT NULL AND NOW() > sla_deadline AND status != 'closed' THEN 1 ELSE 0 END) as sla_violations\n                FROM complaints \n                WHERE c.division = ?","params":["Mumbai"],"caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\ControllerController.php","caller_line":703,"caller_function":"fetch","file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php","line":100}
[2025-09-10 16:40:12] ERROR [Config.php:685] | Called from: index.php:51: EXCEPTION [database.php:110]: Database query failed | Context: {"file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php","line":110,"trace":"#0 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\config\\database.php(115): Database->query('SELECT \\n       ...', Array)\n#1 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\ControllerController.php(703): Database->fetch('SELECT \\n       ...', Array)\n#2 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\controllers\\ControllerController.php(25): ControllerController->getTicketStats(Array)\n#3 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(116): ControllerController->dashboard()\n#4 D:\\Apps\\XAMPP\\htdocs\\testfs\\src\\utils\\Router.php(63): Router->callHandler('Controller@dash...', Array)\n#5 D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php(48): Router->dispatch()\n#6 {main}","caller_file":"D:\\Apps\\XAMPP\\htdocs\\testfs\\public\\index.php","caller_line":51}
